package io.github.illagercpr.thetruth.registry;

import io.github.illagercpr.thetruth.TheTruth;
import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Sound events of The Truth (M8, docs/02 M8 decision 2): the placeholder
 * vanilla sounds of M3 (warden heartbeat, amethyst chime) are replaced by
 * synthesized "data" language audio — short scan pulses instead of organic
 * noises, matching docs/00 §8 (everything is data).
 *
 * <p>All clips are generated by {@code tools/gen_m8_audio.py} into
 * {@code assets/thetruth/sounds/}; the mapping lives in {@code sounds.json}.
 */
public final class TheTruthSounds {

    public static final DeferredRegister<SoundEvent> SOUNDS =
        DeferredRegister.create(Registries.SOUND_EVENT, TheTruth.MOD_ID);

    /** A data stream is ingested (dissolve, restore, experience return). */
    public static final DeferredHolder<SoundEvent, SoundEvent> DATA_INGEST =
        register("data_ingest");

    /** The uncertainty warning opens / ticks down (deep-layer delete front). */
    public static final DeferredHolder<SoundEvent, SoundEvent> UNCERTAINTY_WARNING =
        register("uncertainty_warning");

    /** The salvage window expired: carried matter collapses into unformed data. */
    public static final DeferredHolder<SoundEvent, SoundEvent> UNCERTAINTY_COLLAPSE =
        register("uncertainty_collapse");

    /** Sizes settle back to their records (salvage or recovery). */
    public static final DeferredHolder<SoundEvent, SoundEvent> UNCERTAINTY_SETTLE =
        register("uncertainty_settle");

    /** Middle-layer randomization scrambles stack sizes. */
    public static final DeferredHolder<SoundEvent, SoundEvent> UNCERTAINTY_SCRAMBLE =
        register("uncertainty_scramble");

    private TheTruthSounds() {
    }

    private static DeferredHolder<SoundEvent, SoundEvent> register(final String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(TheTruth.id(name)));
    }
}
